# Generated by Django 4.2 on 2024-03-27 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urusoro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='personne',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=31)),
                ('prenom', models.CharField(max_length=31)),
                ('salaire', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='presence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('present', models.BooleanField()),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='urusoro.personne')),
            ],
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
