# Generated by Django 4.2 on 2024-03-27 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urusoro', '0003_personne_created_at_personne_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='date_adhesion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
