# Generated by Django 4.2 on 2024-03-29 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urusoro', '0005_presence_created_at_presence_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='created_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
