# Generated by Django 4.2 on 2024-04-12 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urusoro', '0007_salaire_personne_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salaire',
            old_name='salaire',
            new_name='montant',
        ),
        migrations.RemoveField(
            model_name='salaire',
            name='nom',
        ),
        migrations.AddField(
            model_name='salaire',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaire',
            name='created_by',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salaire',
            name='personne',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='salaire_personne', to='urusoro.personne'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presence',
            name='personne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presence_personne', to='urusoro.personne'),
        ),
        migrations.AlterField(
            model_name='salaire',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
